import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Button from "@/components/atom/Button";
import { Facebook } from "lucide-react";
import { Instagram } from "lucide-react";
import { Linkedin } from "lucide-react";
import { Phone } from "lucide-react";
import { Mail } from "lucide-react";
import { MapPin } from "lucide-react";
import { Clock } from "lucide-react";
import getSingletonData from "@/data/global";
import ToastProvider from "@/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const globalData = await getSingletonData("Global");
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ToastProvider />
        <nav className="bg-white">
          <div className="container mx-auto px-6 lg:px-26">
            <div className="flex items-center justify-between py-4">
             
              {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "immofrance")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg font-semibold text-immo-primary"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
              <div className="hidden lg:flex items-center gap-x-8">
                 {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "recherche")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                
                 {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "nos_biens")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                
                {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "a_propos")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "blog")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
              </div>
              <div className="hidden lg:block">
                {globalData.NavLink && (
                    <div>
                      {globalData.NavLink
                        .filter((item) => item.label === "nous_contactez")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="text-lg hover:underline"
                          >
                            
                            <Button title={item.visible_name} />
                          </a>
                         
                        ))}
                    </div>
                  )}
              </div>
              <div className="lg:hidden flex items-center gap-x-3">
                <a href={`../#APropos`} className="inline-block">
                  <Button title={"Contact"} />
                </a>
                <label
                  htmlFor="nav-toggle"
                  className="cursor-pointer p-2 rounded-md hover:bg-gray-100"
                  aria-label="Toggle menu"
                >
                  <span className="block w-6 h-0.5 bg-black mb-1"></span>
                  <span className="block w-6 h-0.5 bg-black mb-1"></span>
                  <span className="block w-6 h-0.5 bg-black"></span>
                </label>
              </div>
            </div>
            <input id="nav-toggle" type="checkbox" className="peer hidden" />
            <div className="peer-checked:block hidden lg:hidden pb-4">
              <div className="flex flex-col gap-3">
                <a
                  href="/biens/1"
                  className="block text-base hover:underline px-1"
                >
                  Recherche
                </a>
                <a
                  href="/biens"
                  className="block text-base hover:underline px-1"
                >
                  Nos Biens
                </a>
                <a
                  href="../#APropos"
                  className="block text-base hover:underline px-1"
                >
                  À Propos
                </a>
                <a
                  href="/blog"
                  className="block text-base hover:underline px-1"
                >
                  Nos blogs
                </a>
              </div>
            </div>
          </div>
        </nav>
                  
        {children}
        <footer className="bg-immo-footer text-white">
          <div className="container mx-auto px-6 lg:px-8 py-8">
            <div className="grid grid-cols-1 content-center sm:grid-cols-2 md:grid-cols-4 md:text-left gap-6">
              <div className="sm:pb-4">
                 {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "immofrance")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline mb-4 font-semibold uppercase text-immo-primary"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                <p className="mb-4 font-medium">
                  {globalData.Votre_partenaire}
                </p>

                <div className="flex items-center gap-3">
                  <a href="#" className="p-2 rounded-full hover:bg-red-700">
                    <Facebook size={20} />
                  </a>
                  <a href="#" className="p-2 rounded-full hover:bg-red-700">
                    <Instagram size={20} />
                  </a>
                  <a href="#" className="p-2 rounded-full hover:bg-red-700">
                    <Linkedin size={20} />
                  </a>
                </div>
              </div>

              <div className="sm:pb-4">
                <h2 className="mb-4 font-semibold uppercase">
                  {globalData.Navigation}
                </h2>
                <ul className="font-medium space-y-3">
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "acceuil")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "nos_biens")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "a_propos")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "blog")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                </ul>
              </div>
              <div className="sm:pb-4">
                <h2 className="mb-4 font-semibold uppercase">
                  {globalData.Services}
                </h2>
                <ul className="font-medium space-y-3">
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "achat")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "vente")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "location")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                  <li>
                    {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "gestion_locative")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  </li>
                </ul>
              </div>
              <div className="sm:pb-4">
                <h2 className="mb-4 font-semibold uppercase">
                  {globalData.Contact}
                </h2>
                <ul className="font-medium space-y-3 s:justify-center">
                  <li>
                    <div className="flex items-center gap-2">
                      <Phone size={16} />
                      <p>{globalData.Numero}</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex items-center gap-2">
                      <Mail size={16} />
                      <p>{globalData.adresse_mail}</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex items-center gap-2">
                      <MapPin size={16} />
                      <p>{globalData.adresse}</p>
                    </div>
                  </li>
                  <li>
                    <div className="flex items-center gap-2">
                      <Clock size={16} />
                      <p>{globalData.horaire}</p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
            <div className="border-t border-immo-footer-writing mt-6 pt-4">
              <div className="flex flex-col md:flex-row items-center justify-between gap-4">
                <p className="text-sm">
                  © {new Date().getFullYear()} {globalData.ImmoFrance_text}
                </p>

                <div className="flex flex-wrap items-center gap-4 text-sm">
                  {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "mention légales")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter(
                          (item) =>
                            item.label === "politique_de_confidentialite"
                        )
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                  {globalData.footer_nav && (
                    <div>
                      {globalData.footer_nav
                        .filter((item) => item.label === "plan_du_site")
                        .map((item) => (
                          <a
                            key={item.label}
                            href={item.link}
                            className="hover:underline"
                          >
                            {item.visible_name}
                          </a>
                        ))}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
